universe   = vanilla
getenv     = True
executable = sub.sh
+JobFlavour           = "workday"
requirements = ((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 8

log        = cond/pthat15_unemb_pgoing_nocut.log
output     = cond/pthat15_unemb_pgoing_nocut.out
error      = cond/pthat15_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat15_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_15 1 15 30
queue

log        = cond/pthat30_unemb_pgoing_nocut.log
output     = cond/pthat30_unemb_pgoing_nocut.out
error      = cond/pthat30_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat30_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_30 1 30 50
queue

log        = cond/pthat50_unemb_pgoing_nocut.log
output     = cond/pthat50_unemb_pgoing_nocut.out
error      = cond/pthat50_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat50_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_50 1 50 80
queue

log        = cond/pthat80_unemb_pgoing_nocut.log
output     = cond/pthat80_unemb_pgoing_nocut.out
error      = cond/pthat80_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat80_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_80 1 80 120
queue

log        = cond/pthat120_unemb_pgoing_nocut.log
output     = cond/pthat120_unemb_pgoing_nocut.out
error      = cond/pthat120_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat120_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_120 1 120 170
queue

log        = cond/pthat170_unemb_pgoing_nocut.log
output     = cond/pthat170_unemb_pgoing_nocut.out
error      = cond/pthat170_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat170_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_170 1 170 220
queue

log        = cond/pthat220_unemb_pgoing_nocut.log
output     = cond/pthat220_unemb_pgoing_nocut.out
error      = cond/pthat220_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat220_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_220 1 220 280
queue

log        = cond/pthat280_unemb_pgoing_nocut.log
output     = cond/pthat280_unemb_pgoing_nocut.out
error      = cond/pthat280_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat280_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_280 1 280 370
queue

log        = cond/pthat370_unemb_pgoing_nocut.log
output     = cond/pthat370_unemb_pgoing_nocut.out
error      = cond/pthat370_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat370_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_370 1 370 460
queue

log        = cond/pthat460_unemb_pgoing_nocut.log
output     = cond/pthat460_unemb_pgoing_nocut.out
error      = cond/pthat460_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat460_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_460 1 460 540
queue

log        = cond/pthat540_unemb_pgoing_nocut.log
output     = cond/pthat540_unemb_pgoing_nocut.out
error      = cond/pthat540_unemb_pgoing_nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat540_pgoing_unembedded.txt /eos/user/d/ddesouza/JetResults/Unembedded/Unemb_nocut_pPb_540 1 540 8160
queue
